
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '417fae7a91c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_search_url', sa.String(), nullable=False),
    sa.Column('car_selector', sa.String(), nullable=False),
    sa.Column('title_selector', sa.String(), nullable=False),
    sa.Column('price_selector', sa.String(), nullable=False),
    sa.Column('year_selector', sa.String(), nullable=False),
    sa.Column('mileage_selector', sa.String(), nullable=False),
    sa.Column('fuel_selector', sa.String(), nullable=False),
    sa.Column('transmission_selector', sa.String(), nullable=False),
    sa.Column('engine_capacity_selector', sa.String(), nullable=False),
    sa.Column('seats_selector', sa.String(), nullable=False),
    sa.Column('horse_power_selector', sa.String(), nullable=False),
    sa.Column('link_selector', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scrape_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_brand', sa.String(), nullable=False),
    sa.Column('car_model', sa.String(), nullable=False),
    sa.Column('min_year', sa.Integer(), nullable=True),
    sa.Column('max_year', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraped_cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('marketplace_id', sa.Integer(), nullable=False),
    sa.Column('car_title', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('fuel', sa.String(), nullable=True),
    sa.Column('transmission', sa.String(), nullable=True),
    sa.Column('engine_capacity', sa.String(), nullable=True),
    sa.Column('seats', sa.String(), nullable=True),
    sa.Column('horse_power', sa.String(), nullable=True),
    sa.Column('car_url', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['scrape_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraped_cars')
    op.drop_table('scrape_requests')
    op.drop_table('marketplaces')
    # ### end Alembic commands ###
