"""Added new fields in regression

Revision ID: 61ffa1fb6cad
Revises: 3de6647eb136
Create Date: 2025-06-17 02:14:37.722334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ffa1fb6cad'
down_revision: Union[str, None] = '3de6647eb136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regression_models', sa.Column('adj_r_squared', sa.Float(), nullable=True))
    op.add_column('regression_models', sa.Column('f_statistic', sa.Float(), nullable=True))
    op.add_column('regression_models', sa.Column('f_p_value', sa.Float(), nullable=True))
    op.add_column('regression_models', sa.Column('n_observations', sa.Integer(), nullable=True))
    op.add_column('regression_models', sa.Column('model_summary', sa.JSON(), nullable=True))
    op.add_column('regression_models', sa.Column('standard_errors', sa.JSON(), nullable=True))
    op.add_column('regression_models', sa.Column('t_statistics', sa.JSON(), nullable=True))
    op.add_column('regression_models', sa.Column('p_values', sa.JSON(), nullable=True))
    op.add_column('regression_models', sa.Column('confidence_intervals', sa.JSON(), nullable=True))
    
    # Add updated_at as nullable first
    op.add_column('regression_models', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Set updated_at to current time for existing rows
    op.execute("UPDATE regression_models SET updated_at = created_at")
    
    # Now alter the column to be non-nullable
    op.alter_column('regression_models', 'updated_at', nullable=False)
    
    # Change description type to Text
    op.alter_column('regression_models', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regression_models', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('regression_models', 'updated_at')
    op.drop_column('regression_models', 'confidence_intervals')
    op.drop_column('regression_models', 'p_values')
    op.drop_column('regression_models', 't_statistics')
    op.drop_column('regression_models', 'standard_errors')
    op.drop_column('regression_models', 'model_summary')
    op.drop_column('regression_models', 'n_observations')
    op.drop_column('regression_models', 'f_p_value')
    op.drop_column('regression_models', 'f_statistic')
    op.drop_column('regression_models', 'adj_r_squared')
    # ### end Alembic commands ###
