"""2

Revision ID: 77adfc149a54
Revises: 8492a4049371
Create Date: 2025-06-14 19:34:55.285780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77adfc149a54'
down_revision: Union[str, None] = '8492a4049371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketplaces', 'horse_power_selector',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketplaces', 'horse_power_selector',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
