
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8492a4049371'
down_revision: Union[str, None] = '417fae7a91c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketplaces', 'seats_selector')
    op.drop_column('scraped_cars', 'seats')
    # ### end Alembic commands ###


def downgrade() -> None:
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_cars', sa.Column('seats', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('marketplaces', sa.Column('seats_selector', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
